# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 9, 601, 511))
        self.frame.setStyleSheet("background-color:white;\n"
"border-bottom-right-radius: 50px;\n"
"border-top-left-radius: 50px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(180, 70, 251, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(28)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_select_document = QtWidgets.QPushButton(self.frame)
        self.btn_select_document.setGeometry(QtCore.QRect(140, 350, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(True)
        self.btn_select_document.setFont(font)
        self.btn_select_document.setStyleSheet("background-color:rgb(59, 24, 255);\n"
"color:white\n"
"")
        self.btn_write.clicked.connect(self.parse_document)


        
        self.btn_select_document.setObjectName("btn_select_document")
        self.btn_write = QtWidgets.QPushButton(self.frame)
        self.btn_write.setGeometry(QtCore.QRect(360, 340, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        self.btn_write.setFont(font)
        self.btn_write.setObjectName("btn_write")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "HandWritten"))
        self.btn_select_document.setText(_translate("MainWindow", "Select DUC"))
        self.btn_write.setText(_translate("MainWindow", "writter"))
